baseURL = "https://AH-DevWorks.github.io"
DefaultContentLanguage = "zh-tw"
defaultContentLanguageInSubdir = false
languageCode = "zh-tw"
title = "Meditations in Code - A.H."
theme = "lightbi-hugo"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
#pygmentsUseClasses = true
#pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
#googleAnalytics = "XXX"
enableRobotsTXT = true
enableGitInfo = false
summaryLength  = "30"
ignoreLogs = ['warning-goldmark-raw-html']

[pagination]
pagerSize = 6

[Params]
selfHosted = true
mainSections = ["post","posts"]
dateFormat = "2006年1月2日"
comments = false
readingTime = false
wordCount = false
useHLJS = true
socialShare = true
delayDisqus = true
showRelatedPosts = true
summaryLength  = "9"
lunrSearch = true
gcse = false
lastmod = true
rss = false
pagination = "10"
hideAuthor = false
description="The unexamined life is unworthy of a human being."
previewCardImagePlacement = "top"
showPostImage = false

[Params.Author]
  name = "AH-DevWorks"
  website = "https://ah-devworks.github.io/"
  authorInfo = "All the world’s a stage, and all the men and women merely players. They have their exits and their entrances, and one man in his time plays many parts."
  authorPostImage = ""
  email = "a.h.devworks@gmail.com"
  # facebook = "username"
  # instagram = "username"
  # youtube = "user/username" # or channel/channelname
  # twitter = "username"
  linkedin = "username"
  github = "AH-DevWorks"
  # threads = "username"
  # gitlab = "username"
  # reddit = "username"
  # stackoverflow = "users/XXXXXXX/username"
  # snapchat = "username"
  # spotify = "username"
  # paypal = "username"
  # telegram = "username"
  # mastodon = "url"
  # slack = "username"
  # bandcamp = "username"
  # itchio = "username"
  # vk = "username"
  # 500px = "username"
  # kaggle = "username"
  # weibo = "username"
  # xing = "username"
  # bitbucket = "username"
  # soundcloud = "username"
  # codepen = "username"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Notes"
    url = "/notes/"
    weight = 2

[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3

[[menu.main]]
    name = "Collections"
    url = "/collections/"
    weight = 4

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 5


[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

